#!/usr/bin/env bash

if [ $# -ne 2 ]; then
    echo "Usage: $0 <bucket-name> and the Filename"
    exit 1
fi

BUCKET_NAME=$1
FILE_NAME=$2

FILE_PATH=$(basename "$FILE_NAME")

aws s3api put-object \
  --bucket "$BUCKET_NAME" \
  --body "$FILE_NAME" \
  --key "$FILE_PATH"
