#!/usr/bin/env bash

if [ $# -ne 1 ]; then
    echo "Usage: $0 <bucket-name>"
    exit 1
fi

if [ $# -ne 2 ]; then
    echo "Usage: $0 <bucket-name> and the Filename"
    exit 1
fi

BUCKET_NAME=$1
FILE_NAME=$2

aws s3api put-object \
--bucket $BUCKET_NAME
--Key $FILE_NAME
--body